apiVersion: v1
kind: Service
metadata:
  name: home
spec:
  ports:
  - port: 80
    name: http
    targetPort: 80
  clusterIP: None
  selector:
    app: home
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: home
  labels:
    app: home
spec:
  selector:
    matchLabels:
      app: home
  serviceName: "home"
  replicas: 1
  podManagementPolicy: "Parallel"
  template:
    metadata:
      labels:
        app: home
        type: ms
    spec:
      nodeSelector:
        tier: api
      containers:
      - name: home
        resources:
          requests:
            cpu: "10m"
        image: $IMG
        imagePullPolicy: IfNotPresent
